apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-app

  template:
    metadata:
      labels:
        app: incident-app

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001

      containers:
        - name: incident-app
          image: ghcr.io/kkgill36/incident-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5001

          env:
            - name: DB_PATH
              value: "/data/incidents.db"

          volumeMounts:
            - name: data-storage
              mountPath: /data

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 15

      volumes:
        - name: data-storage
          emptyDir: {}