apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-app
  template:
    metadata:
      labels:
        app: incident-app
    spec:
      containers:
        - name: incident-app
          image: ghcr.io/kkgill36/incident-app:latest
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15