name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:




jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/incident-app:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/kkgill36/incident-app:latest
          format: table
          exit-code: 0
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/incident-app:latest