name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:




jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v2.1.20
        with:
          path: .
          output_path: kics-results
          fail_on: none
          enable_comments: false

  

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/incident-app:${{ github.sha }} .


      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/kkgill36/incident-app:${{ github.sha }}
          format: table
          exit-code: "0"
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/incident-app:${{ github.sha }}
